# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MicroLive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MicroLive
  pod 'MTXKit'

  target 'MicroLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MicroLiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
